name: Run Tests on Nginx Server

on:
  push:

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Separate build and test stages to distinguish image build 
      # failures from test failues in the pipeline. 
      - name: Build docker images
        run: docker compose build

      - name: Run tests with docker compose
        id: run_tests
        run: docker compose up --abort-on-container-exit --exit-code-from test

      - name: Create succeeded file
        if: success()
        run: echo "Tests passed" > succeeded

      - name: Upload succeeded artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-scceeded
          path: succeeded

      - name: Create fail file
        if: failure()
        run: echo "Tests failed" > fail

      - name: Upload fail artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-result-fail
          path: fail

